# .rubocop.yml

AllCops:
  NewCops: disable

require:
  - ./conversion/lib/cops.rb

Style/ArrayInitialization:
  Enabled: true
  InitializeArrayWith: Grizzly::Group

Style/InstanceOfArray:
  Enabled: true
  NewInstanceOf: Grizzly::Group