# .rubocop.yml

AllCops:
  NewCops: disable

require:
  - ./cops/cops.rb

Style/ArrayInitialization:
  Enabled: true
  InitializeArrayWith: "Grizzly::Group"

Style/InstanceOfArray:
  Enabled: true
  NewInstanceOf: "Array"