tests:
  - core/array/compact_spec.rb:21
  - core/array/difference_spec.rb:14
  - core/array/first_spec.rb:76
  - core/array/last_spec.rb:70
  - core/array/pack/buffer_spec.rb:26
  - core/array/partition_spec.rb:37
  - core/array/plus_spec.rb:34
  - core/array/pop_spec.rb:115
  - core/array/reject_spec.rb:36
  - core/array/reverse_spec.rb:18
  - core/array/rotate_spec.rb:63
  - core/array/shared/clone.rb:2
  - core/array/shared/difference.rb:33
  - core/array/shared/intersection.rb:67
  - core/array/shared/select.rb:19
  - core/array/shared/union.rb:62
  - core/array/shift_spec.rb:116
  - core/array/shuffle_spec.rb:24
  - core/array/shuffle_spec.rb:43
  - core/array/shuffle_spec.rb:50
  - core/array/sort_by_spec.rb:16
  - core/array/sort_spec.rb:98
  - core/array/sort_spec.rb:167
  - core/array/sort_spec.rb:229
  - core/array/to_a_spec.rb:5
  - core/array/to_a_spec.rb:11
  - core/array/transpose_spec.rb:47
  - core/array/union_spec.rb:17
  - core/array/values_at_spec.rb:60
